//import "@hotwired/turbo-rails"
import "controllers"
import "jquery"
import "popper"
import "bootstrap.min"
import "jquery.magnific-popup"
import "owl.carousel.min"
import "jquery.nice-select.min"
import "slick.min"
import "jquery.counterup.min"
import "waypoints"
import "contact"
import "jquery.ajaxchimp.min"
import "jquery.form"
import "jquery.validate.min"
import "mail-script"
import "custom"
window.jQuery = window.$ = jQuery
